name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]

body:
  - type: input
    id: version
    attributes:
      label: csvnorm version
      description: Which version are you running? (e.g., v1.0.2)
      placeholder: "v1.0.2"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      description: Output of `python --version`
      placeholder: "Python 3.11.6"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      description: e.g., macOS 14, Ubuntu 22.04, Windows 11
      placeholder: "macOS 14"
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command used
      description: The exact command you ran
      placeholder: "csvnorm input.csv -o output.csv"
      render: shell
    validations:
      required: true

  - type: textarea
    id: input
    attributes:
      label: Input sample (if possible)
      description: Provide a minimal example or a link to the input
      placeholder: |
        name,age
        Alice,30
        Bob,not_a_number
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error output (if any)
      description: Paste any error logs or stderr output
      render: shell
    validations:
      required: false
